### ISSUE TITLE
Getting an environment installation issue. Is this bc of ARM?

### ISSUE THREAD

**Issue by bbhardin** [botcs/wolfson-scheduler#4]
I'm getting the follow issue when I try to run `conda env create -f requirements.yml`. 

Is this because I'm on Apple Silicon? Looks like some of these packages aren't available for Apple Silicon. Or am I missing something else simple? For that matter, does this work on Intel MacOS? Thanks!

    Collecting package metadata (repodata.json): done
    Solving environment: failed
    
    ResolvePackageNotFound: 
      - xz==5.4.2=h5eee18b_0
      - libffi==3.4.4=h6a678d5_0
      - gmpy2==2.1.2=py311hc9b5ff0_0
      - networkx==3.1=py311h06a4308_0
      - psutil==5.9.0=py311h5eee18b_0
      - torchtriton==2.1.0=py311
      - cuda-runtime==12.1.0=0
      - mkl-service==2.4.0=py311h5eee18b_1
      - pytorch==2.1.2=py3.11_cuda12.1_cudnn8.9.2_0
      - bzip2==1.0.8=h7b6447c_0
      - openssl==3.0.12=h7f8727e_0
      - _libgcc_mutex==0.1=main
      - cuda-nvtx==12.1.105=0
      - pandas==1.5.3=py311hba01205_0
      - cuda-nvrtc==12.1.105=0
      - numexpr==2.8.4=py311h65dcdc2_1
      - blas==1.0=mkl
      - libcurand==10.3.4.101=0
      - pip==23.1.2=py311h06a4308_0
      - cuda-libraries==12.1.0=0
      - ca-certificates==2023.08.22=h06a4308_0
      - libnpp==12.0.2.50=0
      - readline==8.2=h5eee18b_0
      - tk==8.6.12=h1ccaba5_0
      - _openmp_mutex==5.1=1_gnu
      - cuda-opencl==12.3.101=0
      - llvm-openmp==14.0.6=h9e868ea_0
      - libcufft==11.0.2.4=0
      - setuptools==67.8.0=py311h06a4308_0
      - mpfr==4.0.2=hb69a4c5_1
      - tbb==2021.8.0=hdb19cb5_0
      - libstdcxx-ng==11.2.0=h1234567_1
      - mkl_fft==1.3.6=py311ha02d727_1
      - libgcc-ng==11.2.0=h1234567_1
      - libcxxabi==14.0.6=h06a4308_0
      - libcublas==12.1.0.26=0
      - ld_impl_linux-64==2.38=h1181459_1
      - pytorch-cuda==12.1=ha16c6d3_5
      - mpmath==1.3.0=py311h06a4308_0
      - sympy==1.12=py311h06a4308_0
      - zlib==1.2.13=h5eee18b_0
      - sqlite==3.41.2=h5eee18b_0
      - libnvjpeg==12.1.1.14=0
      - bottleneck==1.3.5=py311hbed6279_0
      - filelock==3.13.1=py311h06a4308_0
      - pytz==2022.7=py311h06a4308_0
      - libcufile==1.8.1.2=0
      - cuda-cupti==12.1.105=0
      - libcxx==14.0.6=h83ecd13_0
      - ncurses==6.4=h6a678d5_0
      - mpc==1.1.0=h10f8cd9_1
      - yaml==0.2.5=h7b6447c_0
      - mkl==2023.1.0=h213fc3f_46344
      - pyyaml==6.0.1=py311h5eee18b_0
      - gmp==6.2.1=h295c915_3
      - libuuid==1.41.5=h5eee18b_0
      - libcusparse==12.0.2.55=0
      - libcusolver==11.4.4.55=0
      - numpy==1.25.0=py311h08b1b3b_0
      - markupsafe==2.1.1=py311h5eee18b_0
      - intel-openmp==2023.1.0=hdb19cb5_46306
      - numpy-base==1.25.0=py311hf175353_0
      - libnvjitlink==12.1.105=0
      - tqdm==4.65.0=py311h92b7b1e_0
      - typing_extensions==4.7.1=py311h06a4308_0
      - cuda-cudart==12.1.105=0
      - mkl_random==1.2.2=py311ha02d727_1
      - wheel==0.38.4=py311h06a4308_0
      - python==3.11.4=h955ad1f_0
      - jinja2==3.1.2=py311h06a4308_0
      - libgomp==11.2.0=h1234567_1

**Comment by botcs** [comment]
Hey @bbhardin 
Good catch! this is due to over-specification in the conda environment file.

In commit [a660399](https://github.com/botcs/wolfson-scheduler/commit/a660399fb09f345f44245f3ca9e776f1fdf98e76) I have provided `req-cpu.yml` and `req-gpu.yml` with the minimal package specifications:

E.g. the `req-cpu.yml` has only a few lines now, covering the actual packages being used.
Whatever is necessary to install these packages will be pulled by conda on the fly.
```
name: scheduler
channels:
  - pytorch
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.1.2
  - psutil=5.9.0
  - python=3.11
  - pytorch=2.1.2
  - tqdm=4.65.0
  - pip:
      - gspread==6.0.0
```

Updated the README.md as well to reflect the changes
